#!/usr/bin/env bash
# Phase 1 verification: exercises extractor end-to-end against the pinned, checksummed
# flix.jar, verifies determinism (byte-identical across two forked JVMs), structural
# conformance to schemas/{treekind,tokenkind,projection}.schema.json (required keys, types,
# patterns, enums), unit tests, and exact TreeKind/TokenKind counts matching pin.json.
#
# JSON field reads use jq (Category A); anything that walks a real JSON tree -- schema
# validation, coverage, conformance -- is a Gradle-invoked Scala tool in tools/project/src
# (Category B), not a Python script. Scripting on the JVM, never Python: implementation plan
# section 4.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

if [ ! -f .oracle/flix.jar ]; then
  echo "== fetching pinned oracle artifact =="
  ./tools/oracle/fetch.sh
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "== running Gradle test suite =="
./gradlew test

echo "== extracting fixtures/positive/hello.flix twice, checking determinism =="
# JavaExec forks a JVM per invocation, so these are two separate processes.
./gradlew -q :tools:project:extract --args="fixtures/positive/hello.flix" > "$WORK/out1.json"
./gradlew -q :tools:project:extract --args="fixtures/positive/hello.flix" > "$WORK/out2.json"
diff "$WORK/out1.json" "$WORK/out2.json"
echo "OK: byte-identical across two forked JVMs"

echo "== extracting fixtures/negative/unclosed-paren.flix, checking ErrorTree recovery =="
# --form raw is the default and is asserted explicitly here: the whole point of this check is what the
# *reference* did, and the normalized form splices the error vocabulary out on purpose.
./gradlew -q :tools:project:extract --args="--form raw fixtures/negative/unclosed-paren.flix" > "$WORK/broken.json"
grep -q '"kind":"ErrorTree"' "$WORK/broken.json"
echo "OK: parse error recovered into a well-formed tree with an ErrorTree node"

echo "== the normalized form of the same file must carry no error vocabulary =="
./gradlew -q :tools:project:extract --args="--form normalized fixtures/negative/unclosed-paren.flix" \
  > "$WORK/broken-normalized.json"
if grep -q '"kind":"ErrorTree"' "$WORK/broken-normalized.json"; then
  echo "FATAL: the normalized tree still carries error-recovery markers" >&2
  exit 1
fi
# The diagnostics survive: normalization removes the error vocabulary from the tree, never the record
# that the parse failed. Losing those would make negative fixtures indistinguishable from positive ones
# in the form consumers actually read.
jq -e '.units[0].diagnostics | length > 0' "$WORK/broken-normalized.json" > /dev/null
echo "OK: error markers spliced out, diagnostics kept"

echo "== validating committed fixtures against schema and inventory =="
# Both committed forms: fixtures/raw (what the reference produced) and fixtures/expected (that tree
# normalized under ast/transparency.json). Both are published artifacts, so both are gated.
./gradlew -q :tools:project:validateProjection

echo "== regenerating fixtures/raw and fixtures/expected =="
./gradlew -q :tools:project:generateFixtures

echo "== validating regenerated fixtures =="
./gradlew -q :tools:project:validateProjection

echo "== normalization: fixtures/expected must be exactly normalize(fixtures/raw) =="
# The two forms are generated by one run today, which is precisely the state in which the relationship
# stops being checked and later stops being true. Re-deriving it here proves normalization depends only
# on the committed contract and the committed raw tree -- which is what makes fixtures/raw a usable
# authority for the recovery lane rather than merely a copy.
./gradlew -q :tools:project:checkNormalization

echo "== regenerating ast/coverage.json =="
./gradlew -q :tools:project:generateCoverage

echo "== regenerating ast/status.json =="
# Joins coverage with reachability and the curated ast/unattachable.json. Fails when an entry there
# is contradicted by measurement -- a kind claimed unattachable that a fixture or the corpus in fact
# produces -- or when any input disagrees with pin.json about the upstream commit.
./gradlew -q :tools:project:generateStatus

echo "== validating the reference-compiler defect ledger =="
# Re-parses each entry's reproducer against the pinned oracle. An entry that stops reproducing means
# upstream fixed the defect, and fails here so the entry gets closed deliberately rather than rotting
# into folklore. Entries also expire; docs/DEFECTS.md records what that time-based gate costs.
./gradlew -q :tools:project:validateDefects

echo "== regenerating the generated doc blocks =="
# Prose counts were the one class of generated fact CI never diffed, and they drifted: 134 fixtures
# against 136, 184 covered kinds against 186, and a "coverage equals reachability" claim that had
# quietly stopped holding. verify.yml diffs README.md and docs/CONFORMANCE.md alongside ast/.
./gradlew -q :tools:project:generateDocs

echo "== losslessness: trees must reconstruct their source =="
# Oracle-free: compares each tree against its *input*, so unlike every other gate here it needs no
# independent specification and can say something about the reference itself. Catches dropped,
# duplicated or corrupted token text, none of which a structural comparison can see.
./gradlew -q :tools:project:lossless

echo "== conformance: expectations must agree with themselves =="
./gradlew -q :tools:project:conformance --args="--actual fixtures/expected"

echo "== conformance: the three-lane report must be well-formed =="
# The report is the artifact consumers actually read, and it is produced in their repositories where
# nothing here can check it. Generating one from the identity case and validating it is what keeps
# the published shape honest -- including that every lane reaches a verdict rather than one silently
# reporting nothing.
REPORT="$WORK/conformance.json"
./gradlew -q :tools:project:conformance --args="--actual fixtures/expected --report $REPORT" > /dev/null
./gradlew -q :tools:project:validateReport --args="$REPORT"
jq -e '.lanes.oracle_conformance.verdict == "pass"
       and .lanes.source_invariants.verdict == "pass"' "$REPORT" > /dev/null
# fixtures/expected carries no error vocabulary -- that is what normalization did to it -- so a
# consumer shaped like it models no recovery. The lane says so, with the reason, rather than failing
# it for a modelling decision the contract never required.
jq -e '.lanes.recovery_conformance.verdict == "not-applicable"
       and (.lanes.recovery_conformance.notApplicable | length) > 0' "$REPORT" > /dev/null
echo "OK: both applicable lanes pass on the identity case; recovery stands down, with its reason"

echo "== conformance: the recovery lane must pass on a consumer that does model recovery =="
# The identity case for the third lane, and the strongest single assertion about the design: symmetric
# transparency has to compose exactly. fixtures/raw is fed in as a "consumer" whose vocabulary happens
# to be the canonical one, declaring the transparency contract on its own side -- wrappers ignored,
# recovery markers declared as such. Both derived lanes must then reach zero divergences from the same
# input: the first because splicing the markers out of both sides reproduces fixtures/expected, the
# second because leaving them in on both sides reproduces the raw tree.
IDMAP="$WORK/canonical-identity-map.json"
jq -n \
  --slurpfile inventory ast/treekind.json \
  --slurpfile transparency ast/transparency.json \
  '{
     schemaVersion: 1,
     consumer: "canonical-identity",
     description: "Generated by verify.sh. Treats fixtures/raw as a consumer whose vocabulary is the canonical one.",
     mappings: ($inventory[0].kinds | map({key: .name, value: .name}) | from_entries),
     ignored: ($transparency[0].treeKinds | map(select(.rule == "elide") | .name)),
     recoveryMarkers: ($transparency[0].treeKinds | map(select(.recoveryMarker == true) | .name))
   }' > "$IDMAP"
./gradlew -q :tools:project:validateProjectionMap --args="$IDMAP"
RAWREPORT="$WORK/conformance-raw.json"
./gradlew -q :tools:project:conformance \
  --args="--actual fixtures/raw --map $IDMAP --report $RAWREPORT" > /dev/null
./gradlew -q :tools:project:validateReport --args="$RAWREPORT"
jq -e '.lanes.oracle_conformance.verdict == "pass"
       and .lanes.recovery_conformance.verdict == "pass"' "$RAWREPORT" > /dev/null
# Scoped, not universal: the lane must be answerable for the fixtures that recover from something and
# only those. Scoped to everything, or to nothing, it would reach a verdict about the wrong question.
SCOPED="$(jq -r '.lanes.recovery_conformance.fixturesExpected' "$RAWREPORT")"
TOTAL="$(jq -r '.lanes.oracle_conformance.fixturesExpected' "$RAWREPORT")"
if [ "$SCOPED" -eq 0 ] || [ "$SCOPED" -ge "$TOTAL" ]; then
  echo "FATAL: recovery lane is scoped to $SCOPED of $TOTAL fixtures; expected a proper, non-empty subset" >&2
  exit 1
fi
echo "OK: symmetric transparency composes; recovery scoped to $SCOPED of $TOTAL fixtures"

echo "== conformance: a mutated tree must be detected =="
# A comparison that cannot fail is not a check. Rename one kind and drop one child, then require a
# non-zero exit -- otherwise a silently no-op comparator would report every consumer as conforming.
MUT="$WORK/mutated"
cp -r fixtures/expected "$MUT"
jq '.units[0].tree.children[1].kind = "Expr.Binary" | .units[0].tree.children[1].children |= .[:-1]' \
  "$MUT/hello.json" > "$MUT/hello.json.tmp"
mv "$MUT/hello.json.tmp" "$MUT/hello.json"
if ./gradlew -q :tools:project:conformance --args="--actual $MUT" >/dev/null 2>&1; then
  echo "FATAL: conformance passed a deliberately mutated tree" >&2
  exit 1
fi
echo "OK: mutation detected"

echo "== conformance: a recovery-only mutation must be caught by the recovery lane alone =="
# The load-bearing property of the split, and the one a passing run cannot demonstrate. Delete the
# error markers from one raw tree: the first lane cannot see it, because normalization removes those
# nodes from both sides before it looks, and if the second lane cannot see it either then the second
# lane is measuring nothing at all.
RECMUT="$WORK/recovery-mutated"
cp -r fixtures/raw "$RECMUT"
jq 'def strip: if type == "object" and has("kind")
                 then if (.kind | IN("ErrorTree", "OperatorError", "TrailingDot"))
                        then (.children | map(strip) | .[])
                        else .children |= map(strip) end
                 else . end;
    .units |= map(.tree |= strip)' \
  fixtures/raw/unclosed-paren.json > "$RECMUT/unclosed-paren.json"
RECREPORT="$WORK/conformance-recovery-mutated.json"
if ./gradlew -q :tools:project:conformance \
     --args="--actual $RECMUT --map $IDMAP --report $RECREPORT" >/dev/null 2>&1; then
  echo "FATAL: conformance passed a tree with its error-recovery markers removed" >&2
  exit 1
fi
jq -e '.lanes.oracle_conformance.divergenceCount == 0
       and .lanes.oracle_conformance.verdict == "pass"
       and .lanes.recovery_conformance.divergenceCount > 0
       and .lanes.recovery_conformance.verdict == "fail"' "$RECREPORT" > /dev/null
echo "OK: recovery-only damage is invisible to the structural lane and fails the recovery lane"

echo "== validating committed ast/tokenkind.json against schema =="
./gradlew -q :tools:project:validateTokenKind

echo "== generating ast/tokenkind.json via reflection =="
./gradlew -q :tools:project:generateTokenKind

echo "== validating regenerated ast/tokenkind.json against schema =="
./gradlew -q :tools:project:validateTokenKind

echo "== validating committed ast/treekind.json against schema =="
./gradlew -q :tools:project:validateTreeKind

echo "== generating ast/treekind.json via reflection =="
./gradlew -q :tools:project:generateTreeKind

echo "== validating regenerated ast/treekind.json against schema =="
./gradlew -q :tools:project:validateTreeKind

echo "== validating ast/tokenkind.json structure and pin.json digest =="
TOK_EXPECT_COUNT="$(jq -r '.tokenKindCount' pin.json)"
TOK_EXPECT_DIGEST="$(jq -r '.tokenKindDigest' pin.json)"
TOK_ACTUAL_COUNT="$(jq -r '.tokenKindCount' ast/tokenkind.json)"
TOK_ACTUAL_DIGEST="$(jq -r '.tokenKindDigest' ast/tokenkind.json)"

if [ "$TOK_ACTUAL_COUNT" -ne "$TOK_EXPECT_COUNT" ]; then
  echo "FATAL: expected $TOK_EXPECT_COUNT TokenKind items, got $TOK_ACTUAL_COUNT" >&2
  exit 1
fi

if [ "$TOK_ACTUAL_DIGEST" != "$TOK_EXPECT_DIGEST" ]; then
  echo "FATAL: tokenKindDigest mismatch between pin.json and ast/tokenkind.json" >&2
  echo "  pin.json:        $TOK_EXPECT_DIGEST" >&2
  echo "  tokenkind.json:  $TOK_ACTUAL_DIGEST" >&2
  exit 1
fi
echo "OK: ast/tokenkind.json carries exactly $TOK_ACTUAL_COUNT kinds matching pin digest $TOK_ACTUAL_DIGEST"

echo "== validating ast/treekind.json structure and pin.json digest =="
EXPECT_COUNT="$(jq -r '.treeKindCount' pin.json)"
EXPECT_DIGEST="$(jq -r '.treeKindDigest' pin.json)"

ACTUAL_COUNT="$(jq -r '.treeKindCount' ast/treekind.json)"
ACTUAL_DIGEST="$(jq -r '.treeKindDigest' ast/treekind.json)"

if [ "$ACTUAL_COUNT" -ne "$EXPECT_COUNT" ]; then
  echo "FATAL: expected $EXPECT_COUNT TreeKind items, got $ACTUAL_COUNT" >&2
  exit 1
fi

if [ "$ACTUAL_DIGEST" != "$EXPECT_DIGEST" ]; then
  echo "FATAL: treeKindDigest mismatch between pin.json and ast/treekind.json" >&2
  echo "  pin.json:       $EXPECT_DIGEST" >&2
  echo "  treekind.json:  $ACTUAL_DIGEST" >&2
  exit 1
fi
echo "OK: ast/treekind.json carries exactly $ACTUAL_COUNT kinds matching pin digest $ACTUAL_DIGEST"

echo "== all verification checks passed =="
