version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "gradle"
