package flix.spec

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path, Paths}
import java.util.jar.JarFile
import scala.jdk.CollectionConverters._

/** Enumerates Flix's annotation vocabulary by reflection over the pinned oracle, and writes `ast/annotation.json`.
  *
  * This is a third vocabulary, and it exists because the first two cannot express it. `@Deprecated`, `@Test` and the
  * rest are **not** distinct `TokenKind`s: the lexer emits one `TokenKind.Annotation` for all of them and the name
  * survives only in the token's `text`. So `tokenKindDigest` cannot move when an annotation is added, removed or
  * renamed -- the same blind spot that let `ColonColonTight` re-partition `ColonColon` with every gate green.
  *
  * A highlighter colours these names, an IDE completes them, and until now no consumer could get the list from this
  * repository at all. `flix-textmate` carries a hand-written copy that nothing checks against the pin.
  *
  * **Coverage, not validity.** This inventory must never be used to reject an annotation that is not in it. The
  * `Annotation` token is genuinely open: Java interop annotations appear in Flix source and lex identically --
  * `@TestJvmAnnotation` occurs in the corpus, applied to a method of an anonymous JVM class -- and upstream models
  * exactly that with `Annotation.Error(name, loc)`, its catch-all for a name it does not know. What the inventory
  * supports is measurement: which of the reference's own annotations this suite and the corpus actually exercise.
  *
  * The text is read from `toString`, not derived from the class name, because the two differ: `TailRecursive` renders
  * as `@Tailrec`. Deriving it would have produced a vocabulary the reference never emits.
  */
object AnnotationExtractor {

  private val AnnotationClass = "ca.uwaterloo.flix.language.ast.shared.Annotation"
  private val EntryPrefix = "ca/uwaterloo/flix/language/ast/shared/Annotation"
  private val SourceLocationClass = "ca.uwaterloo.flix.language.ast.SourceLocation"

  /** `Error` is upstream's catch-all for an unrecognised name, not a member of the vocabulary. It is excluded by arity:
    * every real annotation takes exactly the source location, `Error` takes a name as well.
    */
  private val CatchAll = "Error"

  /** Bumped when the output format or the selection logic changes. */
  private val ToolVersion = "1.0.0"

  def extractAnnotations(jar: Path): List[String] = {
    val loader = getClass.getClassLoader
    val annotation = loader.loadClass(AnnotationClass)
    val sourceLocation = loader.loadClass(SourceLocationClass)
    val unknownLoc = loader.loadClass(SourceLocationClass + "$").getField("MODULE$").get(null) match {
      case module => module.getClass.getMethod("Unknown").invoke(module)
    }

    val jf = new JarFile(jar.toFile)
    try {
      val names = jf
        .entries()
        .asScala
        .map(_.getName)
        .filter(n => n.startsWith(EntryPrefix) && n.endsWith(".class"))
        .flatMap { n =>
          val binary = n.stripSuffix(".class").replace('/', '.')
          try Some(loader.loadClass(binary))
          catch { case _: Throwable => None }
        }
        .filter(c => annotation.isAssignableFrom(c) && !c.isInterface && c != annotation)
        .filterNot(_.getSimpleName == CatchAll)
        .flatMap { c =>
          // One constructor taking exactly the source location: that is the shape of every real annotation, and it
          // is what separates them from the catch-all without naming the catch-all twice.
          c.getConstructors
            .find(k => k.getParameterTypes.toList == List(sourceLocation))
            .map(k => k.newInstance(unknownLoc).toString)
        }
        .toList
        .distinct
        .sorted

      require(names.nonEmpty, "FATAL: no annotations found -- is the oracle jar on the classpath?")
      require(names.forall(_.startsWith("@")), s"FATAL: annotation text must start with '@': $names")
      names
    } finally jf.close()
  }

  def calculateDigest(names: List[String]): String =
    TreeKindExtractor.sha256Hex(names.sorted.mkString("\n").getBytes(StandardCharsets.UTF_8))

  def formatJson(names: List[String], digest: String, upstreamCommit: String, oracleSha256: String): String = {
    val sb = new StringBuilder
    sb.append("{\n")
    sb.append("  \"schemaVersion\": 1,\n")
    sb.append(s"""  "generatedBy": "AnnotationExtractor",\n""")
    sb.append(s"""  "toolVersion": "$ToolVersion",\n""")
    sb.append(s"""  "upstreamCommit": "$upstreamCommit",\n""")
    sb.append(s"""  "oracleSha256": "$oracleSha256",\n""")
    sb.append(s"""  "annotationCount": ${names.length},\n""")
    sb.append(s"""  "annotationDigest": "$digest",\n""")
    sb.append(
      "  \"note\": \"Generated by reflection over the pinned oracle. The lexer emits a single TokenKind.Annotation " +
        "for every one of these, so the name lives in the token's text and no TokenKind digest can see it change. " +
        "This is a coverage vocabulary, never a validity check: the Annotation token is open, because Java interop " +
        "annotations lex identically and upstream models them with Annotation.Error. Text is read from toString, " +
        "not from the class name, because TailRecursive renders as @Tailrec.\",\n"
    )
    sb.append("  \"annotations\": [\n")
    names.zipWithIndex.foreach { case (n, i) =>
      val comma = if (i < names.length - 1) "," else ""
      sb.append(s"""    {"name": "${ProjectionExtractor.esc(n)}"}$comma\n""")
    }
    sb.append("  ]\n")
    sb.append("}\n")
    sb.toString
  }

  def main(args: Array[String]): Unit = {
    val propose = args.contains("--propose")
    val root = Paths.get("")
    val pin = Json.parseFile(root.resolve("pin.json"))
    val jar = root.resolve(".oracle/flix.jar")

    val names = extractAnnotations(jar)
    val digest = calculateDigest(names)

    if (propose) {
      println("Proposed values for pin.json. Nothing was written and no assertion was made.")
      println(s"""  "annotationCount": ${names.length},""")
      println(s"""  "annotationDigest": "$digest"""")
      println("Copy them into pin.json, then run generateAnnotation to regenerate under assertion.")
      return
    }

    // Two-pass, exactly as the other inventories: the pin carries the expected values and this asserts them, so a
    // vocabulary change enters the repository through a human rather than through a regenerated file.
    val expectedCount = pin.get("annotationCount").map(_.asInt)
    val expectedDigest = pin.get("annotationDigest").map(_.asString)
    (expectedCount, expectedDigest) match {
      case (Some(c), Some(d)) =>
        require(
          names.length == c && digest == d,
          s"FATAL: annotation vocabulary disagrees with pin.json.\n" +
            s"  pin: $c kinds, digest $d\n  jar: ${names.length} kinds, digest $digest\n" +
            "  Run proposeAnnotation, then paste the new values into pin.json."
        )
      case _ =>
        System.err.println("FATAL: pin.json carries no annotationCount/annotationDigest — run proposeAnnotation")
        sys.exit(1)
    }

    val out = root.resolve("ast/annotation.json")
    Files.writeString(
      out,
      formatJson(names, digest, pin("upstream")("commit").asString, pin("oracleArtifact")("sha256").asString),
      StandardCharsets.UTF_8
    )
    // Validate what was just written, rather than trusting the writer. The other inventories have a separate
    // validate task; folding it in here means the generated file can never be committed unvalidated.
    val doc = Json.parseFile(out)
    val schema = Json.parseFile(root.resolve("schemas/annotation.schema.json"))
    val errors = new SchemaValidator.Errors
    SchemaValidator.check(doc, schema, schema, "ast/annotation.json", errors)
    if (!errors.isEmpty) {
      System.err.println("FATAL: ast/annotation.json does not conform to schemas/annotation.schema.json")
      errors.toList.foreach(e => System.err.println(s"  $e"))
      sys.exit(1)
    }

    println(s"Wrote ${names.length} annotations to ${out.toAbsolutePath} with digest $digest")
  }
}
