package flix.spec

import java.nio.file.{Files, Path, Paths}
import scala.jdk.CollectionConverters._

/** Asserts that `fixtures/expected/` really is `normalize(fixtures/raw/)`, tree for tree.
  *
  * Two committed artifacts that are supposed to stand in a stated relationship will not stay in it on trust. Both are
  * generated by the same run of [[ProjectionExtractor]] today, which makes the property look self-evident -- and that
  * is exactly the state in which it stops being checked and later stops being true. A hand-edited expectation, a
  * partial regeneration, or a transparency rule added without regenerating all of them each break it silently, and
  * every downstream number would still look plausible.
  *
  * Re-deriving the relationship here also proves something the extractor cannot prove about itself: normalisation
  * depends only on the committed contract and the committed raw tree, with no residue from the parse that produced
  * them. That is what makes `fixtures/raw` a usable authority for the recovery lane rather than merely a copy.
  *
  * It checks the document headers too, because `form` is the only thing that tells a reader which tree they are
  * holding, and a mislabelled document is worse than an unlabelled one.
  *
  * Usage: `checkNormalization`. Run from the repository root.
  */
object NormalizationCheck {

  private def jsonFiles(dir: Path): List[Path] =
    Files
      .list(dir)
      .iterator()
      .asScala
      .filter(_.getFileName.toString.endsWith(".json"))
      .toList
      .sortBy(_.getFileName.toString)

  def main(args: Array[String]): Unit = {
    val rawDir = Paths.get(ProjectionExtractor.RawDir)
    val normalizedDir = Paths.get(ProjectionExtractor.NormalizedDir)

    List(rawDir, normalizedDir).foreach { dir =>
      if (!Files.isDirectory(dir)) {
        System.err.println(s"FATAL: $dir/ does not exist — run generateFixtures")
        sys.exit(1)
      }
    }

    val contract = Transparency.load()
    val failures = scala.collection.mutable.ListBuffer.empty[String]

    val rawNames = jsonFiles(rawDir).map(_.getFileName.toString)
    val normalizedNames = jsonFiles(normalizedDir).map(_.getFileName.toString)
    rawNames.diff(normalizedNames).foreach(n => failures += s"$n: in ${rawDir}/ but not in ${normalizedDir}/")
    normalizedNames.diff(rawNames).foreach(n => failures += s"$n: in ${normalizedDir}/ but not in ${rawDir}/")

    var checked = 0
    var nodesBefore = 0
    var nodesAfter = 0

    rawNames.intersect(normalizedNames).foreach { name =>
      val raw = Json.parseFile(rawDir.resolve(name))
      val normalized = Json.parseFile(normalizedDir.resolve(name))

      if (raw("form").asString != ProjectionExtractor.RawForm)
        failures += s"$name: ${rawDir}/ document declares form '${raw("form").asString}'"
      if (normalized("form").asString != ProjectionExtractor.NormalizedForm)
        failures += s"$name: ${normalizedDir}/ document declares form '${normalized("form").asString}'"

      val rawUnits = raw("units").asArray
      val normalizedUnits = normalized("units").asArray
      if (rawUnits.length != normalizedUnits.length)
        failures += s"$name: ${rawUnits.length} raw unit(s) against ${normalizedUnits.length} normalized"
      else
        rawUnits.zip(normalizedUnits).zipWithIndex.foreach { case ((rawUnit, normalizedUnit), i) =>
          if (rawUnit("source").asString != normalizedUnit("source").asString)
            failures += s"$name: unit $i names a different source in each form"

          val derived = Normalizer.render(Normalizer.normalize(rawUnit("tree"), contract))
          val committed = Normalizer.render(normalizedUnit("tree"))
          checked += 1
          nodesBefore += count(rawUnit("tree"))
          nodesAfter += count(normalizedUnit("tree"))
          if (derived != committed)
            failures += s"$name: unit $i is not normalize(raw)\n${firstDifference(derived, committed)}"
        }
    }

    if (failures.nonEmpty) {
      System.err.println("FATAL: fixtures/expected is not the normalization of fixtures/raw")
      failures.foreach(f => System.err.println(s"  $f"))
      sys.exit(1)
    }

    val removed = nodesBefore - nodesAfter
    val pct = if (nodesBefore == 0) 0.0 else 100.0 * removed / nodesBefore
    println(
      f"OK: $checked unit(s) in ${normalizedDir} are exactly normalize(${rawDir}) under " +
        f"${contract.entries.length} transparency rule(s); $removed of $nodesBefore nodes removed ($pct%.1f%%)"
    )
  }

  private def count(node: Json): Int =
    node.get("kind") match {
      case None    => 0
      case Some(_) => 1 + node.get("children").map(_.asArray).getOrElse(Nil).map(count).sum
    }

  /** A window around the first differing character. The trees are one long line each, so a raw diff is unreadable and a
    * "they differ" message alone is unactionable.
    */
  private def firstDifference(derived: String, committed: String): String = {
    val at = derived.zip(committed).indexWhere { case (a, b) => a != b } match {
      case -1 => math.min(derived.length, committed.length)
      case i  => i
    }
    def window(s: String) = s.slice(math.max(0, at - 60), math.min(s.length, at + 60))
    s"    at offset $at\n    derived:   …${window(derived)}…\n    committed: …${window(committed)}…"
  }
}
